title: 科技服務資訊週記
description: AI 自動彙整的科技服務官方資訊週報，使用 Manus Plus
theme: jekyll-theme-cayman
og_image: https://lazyjerry.github.io/assets/og-image.png
google_analytics: G-ZS4ZJMKGME
# url: "https://lazyjerry.github.io/weekly-report/"
# author: Lazy Jerry
